/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as RecordedRouteImport } from './routes/recorded'
import { Route as OrientationRouteImport } from './routes/orientation'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FighterBatchRouteImport } from './routes/fighter-batch'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordedRoute = RecordedRouteImport.update({
  id: '/recorded',
  path: '/recorded',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationRoute = OrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FighterBatchRoute = FighterBatchRouteImport.update({
  id: '/fighter-batch',
  path: '/fighter-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/fighter-batch': typeof FighterBatchRoute
  '/founder': typeof FounderRoute
  '/notes': typeof NotesRoute
  '/orientation': typeof OrientationRoute
  '/recorded': typeof RecordedRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/fighter-batch': typeof FighterBatchRoute
  '/founder': typeof FounderRoute
  '/notes': typeof NotesRoute
  '/orientation': typeof OrientationRoute
  '/recorded': typeof RecordedRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/fighter-batch': typeof FighterBatchRoute
  '/founder': typeof FounderRoute
  '/notes': typeof NotesRoute
  '/orientation': typeof OrientationRoute
  '/recorded': typeof RecordedRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admission'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/faq'
    | '/fighter-batch'
    | '/founder'
    | '/notes'
    | '/orientation'
    | '/recorded'
    | '/success-stories'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/faq'
    | '/fighter-batch'
    | '/founder'
    | '/notes'
    | '/orientation'
    | '/recorded'
    | '/success-stories'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admission'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/faq'
    | '/fighter-batch'
    | '/founder'
    | '/notes'
    | '/orientation'
    | '/recorded'
    | '/success-stories'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionRoute: typeof AdmissionRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  FighterBatchRoute: typeof FighterBatchRoute
  FounderRoute: typeof FounderRoute
  NotesRoute: typeof NotesRoute
  OrientationRoute: typeof OrientationRoute
  RecordedRoute: typeof RecordedRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorded': {
      id: '/recorded'
      path: '/recorded'
      fullPath: '/recorded'
      preLoaderRoute: typeof RecordedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientation': {
      id: '/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof OrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fighter-batch': {
      id: '/fighter-batch'
      path: '/fighter-batch'
      fullPath: '/fighter-batch'
      preLoaderRoute: typeof FighterBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionRoute: AdmissionRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  FighterBatchRoute: FighterBatchRoute,
  FounderRoute: FounderRoute,
  NotesRoute: NotesRoute,
  OrientationRoute: OrientationRoute,
  RecordedRoute: RecordedRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
